const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs');const {mock}=require('./fixtures.cjs');
(async()=>{
const browser=await chromium.launch({headless:true,executablePath:process.env.RT_CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage']});const results=[];
async function check(name,fn){if(process.env.RT_TEST_FILTER&&!name.includes(process.env.RT_TEST_FILTER))return;try{await fn();results.push({name,status:'PASS'});console.log('PASS '+name)}catch(e){results.push({name,status:'FAIL',error:e.message});console.log('FAIL '+name+' '+e.message.slice(0,250))}}
async function make(signed=true,width=1366){const p=await browser.newPage({viewport:{width,height:900},reducedMotion:'reduce'});p.errors=[];p.on('pageerror',e=>p.errors.push(e.message));p.calls=await mock(p);if(signed)await p.addInitScript(()=>localStorage.setItem('revenuetrigger_session','qa-session'));return p}
await check('Competitor search, history, market, profile, relationships and watchlist gate',async()=>{
 const p=await make();await p.goto('http://127.0.0.1:8765/competitors');await p.waitForSelector('.competitor-row');await p.locator('#competitorSearch').fill('QA Example');await p.locator('#competitorMarket').selectOption('Phoenix');await p.locator('#competitorDays').selectOption('30');await p.locator('#competitorRun').click();await p.waitForFunction(()=>document.querySelector('#competitorNote').textContent.includes('30-day'));
 assert(p.calls.some(c=>c.path==='/api/competitors'&&c.query.includes('days=30')&&c.query.includes('market=Phoenix')&&c.query.includes('q=QA')));
 await p.locator('.competitor-row .view').click();await p.waitForFunction(()=>document.querySelector('#cpRelationship').textContent.includes('QA Associated Company'));
 assert.match(await p.locator('#cpBody').innerText(),/Repeated/i);assert.match(await p.locator('#cpBody').innerText(),/Synthetic test fixture/i);
 const dialog=p.waitForEvent('dialog').then(async d=>{assert.match(d.message(),/Territory/);await d.accept()});await p.getByRole('button',{name:'Watch competitor',exact:true}).click();await dialog;
 assert.deepEqual(p.errors,[]);const bounds=await p.locator('#competitorProfileModal .modal-card').boundingBox();assert(bounds.y>=0&&bounds.y+bounds.height<=900,'Profile stays inside viewport');await p.locator('#competitorProfileModal .modal-card').evaluate(e=>e.scrollTo({top:0,behavior:'instant'}));await p.screenshot({path:'docs/redesign/screenshots/after-competitor-profile-1366.png'});await p.close();
});
await check('Mobile account, Saved card, modal, navigation and source diagram',async()=>{
 const p=await make(true,390);await p.goto('http://127.0.0.1:8765/signals?saved=1');await p.waitForSelector('.lead');await p.locator('.lead .view').click();await p.waitForSelector('#leadModal.open');assert(await p.locator('#mGrid').isVisible());assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.screenshot({path:'docs/redesign/screenshots/after-opportunity-detail-390.png'});await p.keyboard.press('Escape');await p.locator('.rt-menu summary').click();assert(await p.locator('.rt-menu a[href="/competitors"]').isVisible());await p.locator('.rt-menu a[href="/competitors"]').click();await p.waitForURL('**/competitors');await p.waitForSelector('.competitor-row');await p.locator('.competitor-row .view').click();await p.waitForSelector('#competitorProfileModal.show');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.close();
 const src=await make(false,390);await src.goto('http://127.0.0.1:8765/sources');await src.locator('[data-city="TUCSON"]').click();assert(await src.locator('[data-city="TUCSON"]').evaluate(e=>e.classList.contains('active')));assert.deepEqual(src.errors,[]);await src.close();
});
await check('All six Arizona market filters preserve market request and attribution',async()=>{
 const p=await make(false);await p.goto('http://127.0.0.1:8765/signals');await p.waitForSelector('.lead');for(const m of ['Phoenix','Tempe','Tucson','Scottsdale','Mesa','Chandler']){await p.locator('#market').selectOption(m);await p.waitForFunction(m=>document.querySelector('#feedStatus').textContent.includes(m),m);assert(p.calls.some(c=>c.path==='/api/feed'&&c.query.includes('markets='+m)));await p.locator('#permitCompanyToggle [data-value="not-listed"]').click();if(!(await p.locator('.lead').count()))await p.locator('#permitCompanyToggle [data-value="listed"]').click();assert.equal(await p.locator('.lead').count(),1);await p.locator('.lead .view').click();assert.match(await p.locator('#mGrid').innerText(),/Synthetic test fixture/);await p.keyboard.press('Escape')}assert.deepEqual(p.errors,[]);await p.close();
});
await check('Root failed magic link is cleared and prompts a fresh link',async()=>{const p=await make(false);await p.route('**/api/auth/verify',r=>r.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:'Expired QA link'})}));await p.goto('http://127.0.0.1:8765/#magic=expired');await p.waitForSelector('#signinModal.open');assert.equal(await p.evaluate(()=>location.hash),'');assert.match(await p.locator('#callbackNotice').innerText(),/Expired QA link/);await p.close()});
await check('Direct Signals magic-link callback retains query route state',async()=>{const p=await make(false);await p.goto('http://127.0.0.1:8765/signals?saved=1#magic=qa-token');await p.waitForFunction(()=>document.querySelector('#savedFilter').value==='saved');assert.deepEqual(p.errors,[]);await p.close()});
await check('Final Sources contrast and mobile KPI layout',async()=>{for(const width of [390,1366]){const p=await make(false,width);await p.goto('http://127.0.0.1:8765/sources');await p.waitForLoadState('networkidle');const style=await p.locator('#sourceFlowConsole').evaluate(e=>({bg:getComputedStyle(e).backgroundColor,shadow:getComputedStyle(e).boxShadow}));assert.equal(style.bg,'rgb(251, 250, 246)');assert.equal(style.shadow,'none');await p.screenshot({path:`docs/redesign/screenshots/after-sources-${width}.png`,fullPage:true});await p.goto('http://127.0.0.1:8765/competitors');await p.waitForLoadState('networkidle');await p.screenshot({path:`docs/redesign/screenshots/after-competitors-${width}.png`,fullPage:true});if(width===390){await p.goto('http://127.0.0.1:8765/signals');await p.waitForSelector('.lead');assert.equal(await p.locator('.kpis').evaluate(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length),2)}await p.close()}});
const report=JSON.parse(fs.readFileSync('docs/redesign/test-results.json'));report.results=report.results.filter(x=>!results.some(y=>y.name===x.name)).concat(results);fs.writeFileSync('docs/redesign/test-results.json',JSON.stringify(report,null,2));await browser.close();if(results.some(x=>x.status==='FAIL'))process.exitCode=1;
})();
