const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('fs');const {mock}=require('./fixtures.cjs');
const base='http://127.0.0.1:8765';const results=[];
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.RT_CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage']});
 async function test(name,fn){if(process.env.RT_TEST_FILTER&&!name.includes(process.env.RT_TEST_FILTER))return;try{await fn();results.push({name,status:'PASS'});console.log('PASS '+name)}catch(e){results.push({name,status:'FAIL',error:e.message});console.log('FAIL '+name+' '+e.message.slice(0,300))}}
 async function pageFor(opts={}){const p=await browser.newPage({viewport:{width:opts.width||1366,height:900}});p.errors=[];p.on('pageerror',e=>p.errors.push(e.message));p.calls=await mock(p,opts);if(opts.signed)await p.addInitScript(()=>localStorage.setItem('revenuetrigger_session','qa-session'));if(opts.legacy)await p.addInitScript(()=>localStorage.setItem('signalhound_session','qa-legacy'));return p}
 for(const width of [390,430,768,1366,1920])for(const route of ['/','/signals','/competitors','/sources'])await test(`Layout ${route} at ${width}px`,async()=>{
  const p=await pageFor({width});await p.goto(base+route);await p.waitForLoadState('networkidle');
  assert.deepEqual(p.errors,[]);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'horizontal page overflow');
  if(route==='/')assert.equal(await p.locator('.rt-preview-card').count(),3);
  if(route==='/signals')assert.equal(await p.locator('.lead').count(),3);
  if([390,1366].includes(width))await p.screenshot({path:`docs/redesign/screenshots/after-${route==='/'?'home':route.slice(1)}-${width}.png`,fullPage:true});
  await p.close();
 });
 await test('Feed filters, search, sorting, detail and authoritative temperature',async()=>{
  const p=await pageFor();await p.goto(base+'/signals');await p.waitForSelector('.lead');
  await p.locator('#permitCompanyToggle [data-value="not-listed"]').click();assert.equal(await p.locator('.lead').count(),3);
  await p.locator('#search').fill('Tempe');assert.equal(await p.locator('.lead').count(),1);await p.locator('#search').fill('');
  await p.locator('#minScore').selectOption('80');assert.equal(await p.locator('.lead').count(),1);await p.locator('#minScore').selectOption('0');
  await p.locator('#sortFeed').selectOption('oldest');assert.match(await p.locator('.lead').first().innerText(),/Chandler/);
  await p.locator('#industry').selectOption('Roofing');assert.equal(await p.locator('.lead').count(),0);await p.locator('#industry').selectOption('HVAC');
  await p.locator('.lead .view').first().click();assert.equal(await p.locator('#leadModal').evaluate(e=>e.classList.contains('open')),true);assert.match(await p.locator('#mGrid').innerText(),/Official permit valuation/i);assert.match(await p.locator('#mWhy').innerText(),/Synthetic QA record/);
  await p.keyboard.press('Escape');await p.locator('#market').selectOption('Tempe');await p.waitForFunction(()=>document.querySelectorAll('.lead').length===1);
  assert.deepEqual(p.errors,[]);await p.close();
 });
 await test('Saved route, saved mutation, feedback, preferences, export and logout',async()=>{
  const p=await pageFor({signed:true});await p.goto(base+'/signals?saved=1');await p.waitForSelector('.lead');assert.equal(await p.locator('#savedFilter').inputValue(),'saved');assert.equal(await p.locator('.lead').count(),1);
  await p.locator('.view[data-lead-action]').first().click();await p.locator('[data-feedback="useful"]').click();assert(p.calls.some(c=>c.path==='/api/feedback'&&c.method==='POST'));await p.keyboard.press('Escape');
  await p.locator('.lead .save').click();await p.waitForFunction(()=>document.querySelectorAll('.lead').length===0);assert.equal(await p.locator('.lead').count(),0);assert(p.calls.some(c=>c.path==='/api/saved'&&c.method==='POST'));
  await p.locator('#accountBtn').click();await p.waitForSelector('#accountModal.open');await p.locator('#prefScore').selectOption('60');await p.getByRole('button',{name:'Save preferences',exact:true}).click();assert(p.calls.some(c=>c.path==='/api/preferences'&&c.method==='POST'));
  const download=p.waitForEvent('download');await p.locator('#exportTop').click();await download;
  await p.locator('#accountBtn').click();await p.getByRole('button',{name:'Sign out',exact:true}).click();await p.waitForFunction(()=>!localStorage.getItem('revenuetrigger_session'));assert.equal(await p.evaluate(()=>localStorage.getItem('revenuetrigger_session')),null);assert.deepEqual(p.errors,[]);await p.close();
 });
 await test('Signed-out Saved prompts authentication',async()=>{const p=await pageFor();await p.goto(base+'/signals?saved=1');await p.waitForSelector('#signinModal.open');assert.equal(await p.evaluate(()=>localStorage.getItem('revenuetrigger_return_to')),'/signals?saved=1');await p.close()});
 await test('Root magic callback verifies, stores session, redirects to Signals',async()=>{const p=await pageFor();await p.goto(base+'/#magic=qa-token');await p.waitForURL('**/signals');assert.equal(await p.evaluate(()=>localStorage.getItem('revenuetrigger_session')),'qa-session');await p.waitForSelector('.lead');assert(p.calls.some(c=>c.path==='/api/dashboard'&&c.auth==='Bearer qa-session'));assert.deepEqual(p.errors,[]);await p.close()});
 await test('Legacy session fallback and expired-session public recovery',async()=>{let p=await pageFor({legacy:true});await p.goto(base+'/signals');await p.waitForSelector('.lead');assert(p.calls.some(c=>c.path==='/api/me'&&c.auth==='Bearer qa-legacy'));await p.close();p=await pageFor({signed:true,expired:true});await p.goto(base+'/signals');await p.waitForSelector('.lead');assert.equal(await p.evaluate(()=>localStorage.getItem('revenuetrigger_session')),null);assert.match(await p.locator('#feedStatus').innerText(),/Live/);await p.close()});
 await test('Root checkout success sync and cancellation message',async()=>{let p=await pageFor({signed:true});await p.goto(base+'/?billing=success');await p.waitForFunction(()=>!location.search.includes('billing'));assert(p.calls.some(c=>c.path==='/api/billing/sync'&&c.method==='POST'));assert.match(await p.locator('#callbackNotice').innerText(),/Checkout returned successfully/);await p.close();p=await pageFor();await p.goto(base+'/?billing=cancel');await p.waitForSelector('#callbackNotice:not([hidden])');assert.match(await p.locator('#callbackNotice').innerText(),/Checkout canceled/);await p.close()});
 for(const plan of ['Scout','Hunter','Territory'])await test(`${plan} checkout preserves plan contract`,async()=>{const p=await pageFor({signed:true});await p.goto(base+'/');await p.waitForFunction(()=>document.querySelector('#accountBtn').textContent==='Account');await p.getByRole('button',{name:'Choose '+plan,exact:true}).click();await p.waitForURL('**/?qa-billing=1');assert(p.calls.some(c=>c.path==='/api/billing/checkout'&&JSON.parse(c.body).plan===plan));await p.close()});
 await test('Pending plan survives magic-link return and triggers checkout',async()=>{const p=await pageFor();await p.addInitScript(()=>localStorage.setItem('revenuetrigger_pending_plan','Hunter'));await p.goto(base+'/#magic=qa-token');await p.waitForURL('**/?qa-billing=1');assert(p.calls.some(c=>c.path==='/api/billing/checkout'));await p.close()});
 await test('Manage billing uses existing portal endpoint',async()=>{const p=await pageFor({signed:true});await p.goto(base+'/signals?account=1');await p.waitForSelector('#accountModal.open');await p.locator('#billingBtn').click();await p.waitForURL('**/?qa-billing=1');assert(p.calls.some(c=>c.path==='/api/billing/portal'));await p.close()});
 await test('Passwordless request contract',async()=>{const p=await pageFor();await p.goto(base+'/');await p.locator('#accountBtn').click();await p.locator('#signinEmail').fill('qa@example.test');await p.locator('#signinForm button').click();await p.waitForFunction(()=>document.querySelector('#signinNotice').textContent.includes('Check your email'));assert(p.calls.some(c=>c.path==='/api/auth/request'&&JSON.parse(c.body).email==='qa@example.test'));await p.close()});
 await test('API failure never substitutes sample leads',async()=>{const p=await pageFor({fail:['/leads','/pipeline']});await p.goto(base+'/');await p.waitForFunction(()=>document.querySelector('#heroState').textContent==='Feed unavailable');assert.equal(await p.locator('.rt-preview-card').count(),0);await p.goto(base+'/signals');await p.waitForFunction(()=>document.querySelector('#feedStatus').textContent.includes('unavailable'));assert.equal(await p.locator('.lead').count(),0);assert.match(await p.locator('#pipelineStatus').innerText(),/unavailable/);assert.deepEqual(p.errors,[]);await p.close()});
 await test('Pipeline degraded state survives filtering and detail works',async()=>{const p=await pageFor({degraded:true});await p.goto(base+'/signals#pipeline');await p.waitForSelector('.pipeline-lead');await p.locator('#pipelineMinScore').selectOption('60');assert.match(await p.locator('#pipelineStatus').innerText(),/degraded/i);await p.locator('.pipeline-lead .view').first().click();await p.waitForSelector('#pipelineModal.open');assert.match(await p.locator('#pWhy').innerText(),/Synthetic QA record/);await p.close()});
 await test('Shared UI does not invent missing intelligence or temperature',async()=>{const p=await pageFor();await p.goto(base+'/');const result=await p.evaluate(()=>({timeline:RTUI.triggerTimeline({}),badge:RTUI.badge({score:99,temperature:'WATCH'}),preview:RTUI.opportunityCard({name:'<script>unsafe</script>',market:'Phoenix'},{preview:true})}));assert.equal(result.timeline,'');assert.match(result.badge,/WATCH/);assert(!result.badge.includes('HOT'));assert(!result.preview.includes('<script>'));await p.close()});
 if(process.env.RT_TEST_FILTER){const previous=JSON.parse(fs.readFileSync('docs/redesign/test-results.json')).results;results.unshift(...previous.filter(x=>!results.some(r=>r.name===x.name)))}
 fs.writeFileSync('docs/redesign/test-results.json',JSON.stringify({data:'Synthetic QA fixtures; all external network requests intercepted. No production/API/Stripe end-to-end verification.',results},null,2));await browser.close();if(results.some(x=>x.status==='FAIL'))process.exitCode=1;
})();
