export const DFW_SOURCES = Object.freeze({
  fortWorthPermits: Object.freeze({
    key: 'fort_worth_development_permits',
    market: 'Fort Worth',
    jurisdiction: 'City of Fort Worth',
    live: true,
    status: 'production-ready',
    kind: 'arcgis-feature-table',
    refresh: 'hourly during business hours',
    url: 'https://services5.arcgis.com/3ddLCBXe1bRt7mzj/arcgis/rest/services/CFW_Open_Data_Development_Permits_View/FeatureServer/0',
    sourcePage: 'https://data.fortworthtexas.gov/',
    license: 'CC-BY-4.0',
  }),
  fortWorthOccupancy: Object.freeze({
    key: 'fort_worth_certificates_of_occupancy',
    market: 'Fort Worth',
    jurisdiction: 'City of Fort Worth',
    live: true,
    status: 'production-ready',
    kind: 'arcgis-feature-table',
    refresh: 'weekdays around 7am',
    url: 'https://services5.arcgis.com/3ddLCBXe1bRt7mzj/arcgis/rest/services/CFW_Open_Data_Certificates_of_Occupancy_Table_view/FeatureServer/0',
    sourcePage: 'https://data.fortworthtexas.gov/',
    license: 'CC-BY-4.0',
  }),
  fortWorthZoningCases: Object.freeze({
    key: 'fort_worth_zoning_cases_current',
    market: 'Fort Worth',
    jurisdiction: 'City of Fort Worth',
    live: true,
    status: 'enrichment-ready',
    kind: 'arcgis-feature-layer',
    url: 'https://mapit.fortworthtexas.gov/ags/rest/services/Planning_Development/Zoning/MapServer/3',
  }),
  dallasNow: Object.freeze({
    key: 'dallas_dallasnow_accela',
    market: 'Dallas',
    jurisdiction: 'City of Dallas',
    live: true,
    status: 'provisional',
    kind: 'accela-public-portal',
    url: 'https://aca-prod.accela.com/DALLASTX/Cap/CapHome.aspx?TabName=Building&module=Building',
    reports: ['Building Active', 'Building Issued', 'Building Submitted'],
    note: 'Public current building-permit system. Stable machine-readable export path still requires validation before production enablement.',
  }),
  dallasCommercialDashboard: Object.freeze({
    key: 'dallas_commercial_permit_dashboard',
    market: 'Dallas',
    jurisdiction: 'City of Dallas',
    live: true,
    status: 'provisional',
    kind: 'tableau-dashboard',
    url: 'https://dallascitydata.dallascityhall.com/views/CommercialPermits_17600436974140/CommercialPermits',
    note: 'Official current commercial permit dashboard; direct CSV/render probes have not produced a stable ingestion contract.',
  }),
  dallasRightOfWayPermits: Object.freeze({
    key: 'dallas_right_of_way_permits',
    market: 'Dallas',
    jurisdiction: 'City of Dallas',
    live: true,
    status: 'supplemental-ready',
    kind: 'arcgis-map-table',
    url: 'https://gis.dallascityhall.com/arcgis/rest/services/Pbw_public/ROWMSPermits/MapServer/2',
    sourcePage: 'https://gis.dallascityhall.com/arcgis/rest/services/Pbw_public/ROWMSPermits/MapServer',
    note: 'Current public Right-of-Way permit details. Useful as a supplemental construction/early-pipeline signal; not a substitute for DallasNow building permits.',
  }),
  dallasRightOfWayLocations: Object.freeze({
    key: 'dallas_right_of_way_locations',
    market: 'Dallas',
    jurisdiction: 'City of Dallas',
    live: true,
    status: 'supporting-ready',
    kind: 'arcgis-map-table',
    url: 'https://gis.dallascityhall.com/arcgis/rest/services/Pbw_public/ROWMSPermits/MapServer/4',
    sourcePage: 'https://gis.dallascityhall.com/arcgis/rest/services/Pbw_public/ROWMSPermits/MapServer',
    note: 'Supporting location table joined to ROW permit detail by EXTERNALFILENUM.',
  }),
  dallasHistoricalPermits: Object.freeze({
    key: 'dallas_historical_building_permits',
    market: 'Dallas',
    jurisdiction: 'City of Dallas',
    live: false,
    status: 'backfill-only',
    kind: 'socrata',
    datasetId: 'e7gq-4sah',
    url: 'https://www.dallasopendata.com/resource/e7gq-4sah.json',
    note: 'Official historical dataset. City explicitly states this dataset is no longer updated after migration to DallasNow.',
  }),
  dallasZoning: Object.freeze({
    key: 'dallas_zoning',
    market: 'Dallas',
    jurisdiction: 'City of Dallas',
    live: true,
    status: 'enrichment-ready',
    kind: 'arcgis-map-service',
    url: 'https://gis.dallascityhall.com/arcgis/rest/services/sdc_public/Zoning/MapServer',
  }),
  dallasPdSup: Object.freeze({
    key: 'dallas_pd_sup_search',
    market: 'Dallas',
    jurisdiction: 'City of Dallas',
    live: true,
    status: 'enrichment-ready',
    kind: 'arcgis-map-service',
    url: 'https://gis.dallascityhall.com/arcgis/rest/services/sdc_public/PD_SUP_Search/MapServer',
  }),
});
